Added delete method
jiririedl/php-sendy pull request #3
Opened 2017-09-22 08:27 UTC by gvidal

According to the api: https://sendy.co/api, there is a missing delete method.

2017-09-25 12:12 UTC, jiririedl requested changes
please make these small cosmetics changes and send me PR again. Great work! Thanks for contrib!

2017-09-25 12:12 UTC, jiririedl commented on src/Sendy.php
> +     * Create campaign API URI
Please change to "Delete subscriber API URL"

2017-09-25 12:12 UTC, jiririedl commented on src/Sendy.php
> +    CONST URI_DELETE = 'api/subscribers/delete.php';
Please refactor const name to URI_DELETE_SUBSCRIBER
Const names fits with section in https://sendy.co/api

2017-09-26 07:39 UTC, gvidal commented
Sure thing! It is done, thank you so much, didn't realized about the typo on the comment.

2017-09-26 08:54 UTC, merged